# fly.toml app configuration file generated for mom-birthday-card on 2025-04-15T20:33:48+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mom-birthday-card'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
